package com.adasoft.phase.rest;

/**
 * This file is generated by the PhaseGenerator
 */
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseOutputFilter;

/**
 * Generated class definition
 */
public class MESRtPhaseOutputRest0100Filter extends MESGeneratedRtPhaseOutputRest0100Filter //nl
                                                                implements IMESRtPhaseOutputFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated method definition
     *
     * @param server The Server object
     */
    public MESRtPhaseOutputRest0100Filter(Server server) {
        super(server);
    }

    /**
     * Generated method definition
     *
     */
    public MESRtPhaseOutputRest0100Filter() {
        super();
    }
}
