package com.adasoft.phase.rest;

import com.rockwell.mes.commons.shared.phase.mvc.AbstractPhaseActionView0200;

/**
 * TODO: Runtime phase action view.
 * <p>
 * Skeleton generated by the PhaseLibManager.
 * <p>
 * 
 * TODO: @author UserName, (c) Copyright 2013 Rockwell Automation Technologies, Inc. All Rights Reserved.
 */
public class RtPhaseActionViewRest0100 extends AbstractPhaseActionView0200<RtPhaseModelRest0100> {

    /** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;

    /**
     * @param theModel the given model
     */
    public RtPhaseActionViewRest0100(final RtPhaseModelRest0100 theModel) {
        super(theModel);
    }

}
