package com.adasoft.phase.rest;

import com.rockwell.mes.commons.shared.phase.mvc.AbstractPhaseExceptionView0200;

/**
 * TODO: Runtime phase exception view.
 * <p>
 * Skeleton generated by the PhaseLibManager.
 * <p>
 * 
 * TODO: @author UserName, (c) Copyright 2013 Rockwell Automation Technologies, Inc. All Rights Reserved.
 */
public class RtPhaseExceptionViewRest0100 extends AbstractPhaseExceptionView0200<RtPhaseModelRest0100> {

    /** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;

    /**
     * @param theModel the given model
     */
    public RtPhaseExceptionViewRest0100(final RtPhaseModelRest0100 theModel) {
        super(theModel);
    }

    @Override
    protected void createUI() {
    }

}
