package com.adasoft.phase.rest;

import com.rockwell.mes.commons.shared.phase.mvc.AbstractPhaseModel0200;

/**
 * TODO: Runtime phase model.
 * <p>
 * Skeleton generated by the PhaseLibManager.
 * <p>
 * 
 * TODO: @author UserName, (c) Copyright 2013 Rockwell Automation Technologies, Inc. All Rights Reserved.
 */
public class RtPhaseModelRest0100 extends AbstractPhaseModel0200 {

    /**
     * @param inPhaseExecutor The phase executor of this model
     */
    protected RtPhaseModelRest0100(final RtPhaseExecutorRest0100 inPhaseExecutor) {
        super(inPhaseExecutor);
    }

    /**
     * @return Returns the executor.
     */
    public RtPhaseExecutorRest0100 getExecutor() {
        return (RtPhaseExecutorRest0100) executor;
    }

    @Override
    public boolean init() {
        // TODO Auto-generated method stub
        return true;
    }
}
