package com.adasoft.phase.label_printer;

import java.util.logging.Logger;

import com.rockwell.mes.commons.shared.phase.mvc.AbstractPhaseModel0200;

/**
 * TODO: Runtime phase model.
 * <p>
 * Skeleton generated by the PhaseLibManager.
 * <p>
 * 
 * TODO: @author UserName, (c) Copyright 2013 Rockwell Automation Technologies, Inc. All Rights Reserved.
 */
public class RtPhaseModelDenLP0100 extends AbstractPhaseModel0200 {

    /**
     * @param inPhaseExecutor The phase executor of this model
     */
    protected RtPhaseModelDenLP0100(final RtPhaseExecutorDenLP0100 inPhaseExecutor) {
        super(inPhaseExecutor);
    }

    /**
     * @return Returns the executor.
     */
    public RtPhaseExecutorDenLP0100 getExecutor() {
        return (RtPhaseExecutorDenLP0100) executor;
    }

    @Override
    public boolean init() {
    	
        return true;
    }
}
