package com.adasoft.phase.label_printer;

import com.rockwell.mes.commons.shared.phase.mvc.AbstractPhaseActionView0200;

/**
 * TODO: Runtime phase action view.
 * <p>
 * Skeleton generated by the PhaseLibManager.
 * <p>
 * 
 * TODO: @author UserName, (c) Copyright 2013 Rockwell Automation Technologies, Inc. All Rights Reserved.
 */
public class RtPhaseActionViewDenLP0100 extends AbstractPhaseActionView0200<RtPhaseModelDenLP0100> {

    /** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;

    /**
     * @param theModel the given model
     */
    public RtPhaseActionViewDenLP0100(final RtPhaseModelDenLP0100 theModel) {
        super(theModel);
    }

}
