package com.adasoft.phase.equipment;

/**
 * This file is generated by the PhaseGenerator
 *
 * Please do not modify this file manually !!
 */
import java.util.List;

import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;
import com.rockwell.mes.commons.base.ifc.objects.MESATObjectFilter;
import com.rockwell.mes.commons.base.ifc.services.PCContext;
import com.rockwell.mes.services.s88.ifc.execution.IMESRtPhase;

import com.rockwell.mes.services.s88equipment.ifc.IMESS88Equipment; 


/**
 * Generated class definition
 */
public abstract class MESGeneratedRtPhaseOutputEQUIP0100Filter extends MESATObjectFilter  {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /** Generated attribute definition */
    private static final String ATDEFINITION_NAME = "AD_PhOutEQUIP0100";

    /**
     * Generated method definition
     *
     * @param server The Server object
     */
    public MESGeneratedRtPhaseOutputEQUIP0100Filter(Server server) {
        super(server, ATDEFINITION_NAME);
    }

    /**
     * Generated method definition
     *
     */
    public MESGeneratedRtPhaseOutputEQUIP0100Filter() {
        super(PCContext.getServerImpl(), ATDEFINITION_NAME);
    }

    /**
     * Generated method definition
     *
     * @return the list of the objects
     */
    @Override
    public List<MESRtPhaseOutputEQUIP0100> getFilteredObjects () {
        return MESATObject.getFilteredMESATObjectList(this, MESRtPhaseOutputEQUIP0100.class);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseOutputEQUIP0100Filter forParentEqualTo(IMESRtPhase value) //
            throws DatasweepException {
        String columnName = MESRtPhaseOutputEQUIP0100.COL_NAME_PARENT;
        return (MESRtPhaseOutputEQUIP0100Filter) forColumnNameEqualTo(columnName, Long.valueOf(value.getKey()));
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseOutputEQUIP0100Filter forParentNotEqualTo(IMESRtPhase value) //
            throws DatasweepException {
        String columnName = MESRtPhaseOutputEQUIP0100.COL_NAME_PARENT;
        return (MESRtPhaseOutputEQUIP0100Filter) forColumnNameNotEqualTo(columnName, Long.valueOf(value.getKey()));
    }



    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseOutputEQUIP0100Filter forValuesEqualTo(byte[] value) //
            throws DatasweepException {
        return (MESRtPhaseOutputEQUIP0100Filter) forColumnNameEqualTo("AD_Values", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseOutputEQUIP0100Filter forValuesNotEqualTo(byte[] value) //
            throws DatasweepException {
        return (MESRtPhaseOutputEQUIP0100Filter) forColumnNameNotEqualTo("AD_Values", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseOutputEQUIP0100Filter forEquipmentEntityEqualTo(IMESS88Equipment value) //
            throws DatasweepException {
        return (MESRtPhaseOutputEQUIP0100Filter) forColumnNameEqualTo("AD_EquipmentEntity", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseOutputEQUIP0100Filter forEquipmentEntityNotEqualTo(IMESS88Equipment value) //
            throws DatasweepException {
        return (MESRtPhaseOutputEQUIP0100Filter) forColumnNameNotEqualTo("AD_EquipmentEntity", value);
    }


    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseOutputEQUIP0100Filter forExceptionRecordedEqualTo(Boolean value) //
            throws DatasweepException {
        return (MESRtPhaseOutputEQUIP0100Filter) forColumnNameEqualTo("AD_ExceptionRecorded", value);
    }

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException the PC exception
     */
    public MESRtPhaseOutputEQUIP0100Filter forExceptionRecordedNotEqualTo(Boolean value) //
            throws DatasweepException {
        return (MESRtPhaseOutputEQUIP0100Filter) forColumnNameNotEqualTo("AD_ExceptionRecorded", value);
    }

}
