package com.adasoft.phase.equipment;

/**
 * This file is generated by the PhaseGenerator
 */
import com.datasweep.compatibility.client.ATRow;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseOutput;

/**
 * Generated class definition
 */
public class MESRtPhaseOutputEQUIP0100 extends MESGeneratedRtPhaseOutputEQUIP0100 implements IMESRtPhaseOutput {

    /**
     * Generated constructor (from DB key)
     *
     * @param key The key of the ATRow to load.
     */
    public MESRtPhaseOutputEQUIP0100(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESRtPhaseOutputEQUIP0100(MESRtPhaseOutputEQUIP0100 source) {
        super(source);
    }

    /**
     * Generated constructor (from ATRow)
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESRtPhaseOutputEQUIP0100(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESRtPhaseOutputEQUIP0100() {
        super();
    }

}
