package com.adasoft.phase.equipment;

import com.rockwell.mes.commons.shared.phase.mvc.AbstractPhaseActionView0200;

/**
 * TODO: Runtime phase action view.
 * <p>
 * Skeleton generated by the PhaseLibManager.
 * <p>
 * 
 * TODO: @author UserName, (c) Copyright 2013 Rockwell Automation Technologies, Inc. All Rights Reserved.
 */
public class RtPhaseActionViewEQUIP0100 extends AbstractPhaseActionView0200<RtPhaseModelEQUIP0100> {

    /** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;

    /**
     * @param theModel the given model
     */
    public RtPhaseActionViewEQUIP0100(final RtPhaseModelEQUIP0100 theModel) {
        super(theModel);
    }

}
