package com.adasoft.phase.equipment;

import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

import javax.swing.JLabel;
import javax.swing.JPanel;

import com.rockwell.mes.apps.ebr.ifc.phase.ui.UIConstants;
import com.rockwell.mes.apps.ebr.ifc.swing.PhaseColumnLayout.Column;
import com.rockwell.mes.apps.ebr.ifc.swing.PhaseSwingHelper;
import com.rockwell.mes.commons.shared.phase.mvc.AbstractPhaseMainView0200;
import com.rockwell.mes.commons.shared.phase.viewhelper.swing.LayoutHelper0201;

/**
 * TODO: Runtime phase view.
 * <p>
 * Skeleton generated by the PhaseLibManager.
 * <p>
 * 
 * TODO: @author UserName, (c) Copyright 2013 Rockwell Automation Technologies, Inc. All Rights Reserved.
 */
public class RtPhaseViewEQUIP0100 extends AbstractPhaseMainView0200<RtPhaseModelEQUIP0100> {

    /** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;

    /**
     * @param theModel The model of this view
     */
    protected RtPhaseViewEQUIP0100(final RtPhaseModelEQUIP0100 theModel) {
        super(theModel);
    }

    @Override
    protected String getNavigatorInfoColumn() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected void createUI() {
        // CHECKSTYLE:MagicNumber:off (Reason: Columns, rows and width up to 3 ...)

        setOpaque(false);
        this.setLayout(new GridBagLayout());
        GridBagConstraints gbConstraints = new GridBagConstraints();

        gbConstraints.anchor = GridBagConstraints.FIRST_LINE_START;
        LayoutHelper0201.setGBConstraints(gbConstraints, 0, 0, 3, 1);
        add(createInstructionPanel(getModel().getInstructionTextColumn1(), LayoutHelper0201.calculatePreferredWidth(gbConstraints)), gbConstraints);

        LayoutHelper0201.setGBConstraints(gbConstraints, 0, 1, 3, 1);
        add(createActionPanel(LayoutHelper0201.calculatePreferredWidth(gbConstraints)),
                gbConstraints);

        gbConstraints.anchor = GridBagConstraints.PAGE_END;
        LayoutHelper0201.setGBConstraints(gbConstraints, 3, 1, 1, 1);
        add(createConfirmPanel(), gbConstraints);

        // CHECKSTYLE:MagicNumber:on
    }

    /**
     * @param preferredWidth the preferred width.
     * @return The action panel
     */
    protected Component createActionPanel(int preferredWidth) {
        JPanel layoutPanel = PhaseSwingHelper.createPanel();
        ((FlowLayout) layoutPanel.getLayout()).setHgap(UIConstants.DEFAULT_GAP);
        ((FlowLayout) layoutPanel.getLayout()).setVgap(UIConstants.DEFAULT_GAP);
        JLabel label =
                PhaseSwingHelper.createMultiLineLabel("Hello World. Consider I18N.", layoutPanel, preferredWidth - (UIConstants.DEFAULT_GAP * 2));
        layoutPanel.add(label, Column.FIRST_COLUMN);
        return layoutPanel;
    }

}
