package com.adasoft.gv.phase.product.labelgenerator;

/**
 * This file is generated by the PhaseGenerator
 *
 * Please do not modify this file manually !!
 */
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import com.datasweep.compatibility.client.ATRow;
import com.datasweep.compatibility.client.Response;
import com.rockwell.mes.commons.base.ifc.utility.ObjectFactory;
import com.rockwell.mes.services.s88.ifc.library.IBuildingBlockOutputDescriptor;
import com.rockwell.mes.services.s88.ifc.processdata.MESRtPhaseOutput;

import com.rockwell.mes.commons.base.ifc.utility.StringUtilsEx;

 /**
 * Generated class definition
 * <br/>Application table: GVPhOutLabelGen0100
 */
public abstract class MESGeneratedRtPhaseOutputLabelGen0100
 extends MESRtPhaseOutput {

    /** Generated attribute definition */
    protected static final String ATDEFINITION_NAME = "GVPhOutLabelGen0100";


    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedRtPhaseOutputLabelGen0100(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source the source to copy.
     */
    public MESGeneratedRtPhaseOutputLabelGen0100(MESGeneratedRtPhaseOutputLabelGen0100 source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedRtPhaseOutputLabelGen0100(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated constructor
     */
    public MESGeneratedRtPhaseOutputLabelGen0100() {
        super();
    }

    @Override
    protected void synchronizeAfterATRowRefresh() {
        super.synchronizeAfterATRowRefresh();
    }    
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getName() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("GVName"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setName(String value) {
        String oldValue = this.getName();
        this.dgtATRow.setValue("GVName", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("name", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getDescription() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("GVDescription"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setDescription(String value) {
        String oldValue = this.getDescription();
        this.dgtATRow.setValue("GVDescription", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("description", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getValue() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("GVValue"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setValue(String value) {
        String oldValue = this.getValue();
        this.dgtATRow.setValue("GVValue", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("value", oldValue, value);
    }
    
    @Override
    protected Response prepareATRowForSave() {
        // Check if transient references are valid and store the corresponding keys in the ATRow:
        Response res = super.prepareATRowForSave();

        return res;
    }

    /** output descriptors */
    private static final List<IBuildingBlockOutputDescriptor> OUTPUT_DESCRIPTORS =
            new ArrayList<IBuildingBlockOutputDescriptor>();

    /**
     * Initializes the output descriptors.
     */
    static {
        IBuildingBlockOutputDescriptor descriptor;

        descriptor = ObjectFactory.getInstance().createObject(IBuildingBlockOutputDescriptor.class,
                           new Class[] { String.class, String.class, Class.class },
                           new Object[] { "Name", "Label Name", String.class }
                          );
        OUTPUT_DESCRIPTORS.add(descriptor);

        descriptor = ObjectFactory.getInstance().createObject(IBuildingBlockOutputDescriptor.class,
                           new Class[] { String.class, String.class, Class.class },
                           new Object[] { "Description", "Label Description", String.class }
                          );
        OUTPUT_DESCRIPTORS.add(descriptor);

        descriptor = ObjectFactory.getInstance().createObject(IBuildingBlockOutputDescriptor.class,
                           new Class[] { String.class, String.class, Class.class },
                           new Object[] { "Value", "Label Value", String.class }
                          );
        OUTPUT_DESCRIPTORS.add(descriptor);
    }

    /**
     * Retrieves the output descriptors of this class.
     *  
     * @return unmodifiable list of output descriptors
     */
    public static List<IBuildingBlockOutputDescriptor> getOutputDescriptorsOfClass() {
        return Collections.unmodifiableList(OUTPUT_DESCRIPTORS);
    }
    
    @Override
    public List<IBuildingBlockOutputDescriptor> getOutputDescriptors() {
        return getOutputDescriptorsOfClass();
    }
    
}
