package com.adasoft.gv.phase.product.labelgenerator;

/**
 * This file is generated by the PhaseGenerator
 *
 * Please do not modify this file manually !!
 */

import com.datasweep.compatibility.client.ATRow;
import com.datasweep.compatibility.client.Response;
import com.rockwell.mes.services.s88.ifc.processdata.MESRtPhaseData;

import com.rockwell.mes.commons.base.ifc.utility.StringUtilsEx;
import java.math.BigDecimal;

 /**
 * Generated class definition
 * <br/>Application table: GVPhDatLabelGen0100
 */
public abstract class MESGeneratedRtPhaseDataLabelGen0100
 extends MESRtPhaseData {

    /** Generated attribute definition */
    protected static final String ATDEFINITION_NAME = "GVPhDatLabelGen0100";


    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedRtPhaseDataLabelGen0100(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source the source to copy.
     */
    public MESGeneratedRtPhaseDataLabelGen0100(MESGeneratedRtPhaseDataLabelGen0100 source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedRtPhaseDataLabelGen0100(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated constructor
     */
    public MESGeneratedRtPhaseDataLabelGen0100() {
        super();
    }

    @Override
    protected void synchronizeAfterATRowRefresh() {
        super.synchronizeAfterATRowRefresh();
    }    
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getName() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("GVName"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setName(String value) {
        String oldValue = this.getName();
        this.dgtATRow.setValue("GVName", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("name", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getDescription() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("GVDescription"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setDescription(String value) {
        String oldValue = this.getDescription();
        this.dgtATRow.setValue("GVDescription", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("description", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public BigDecimal getValue() {
        return (BigDecimal) this.dgtATRow.getValue("GVValue");
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setValue(BigDecimal value) {
        BigDecimal oldValue = this.getValue();
        this.dgtATRow.setValue("GVValue", value);
        pcs.firePropertyChange("value", oldValue, value);
    }

    @Override
    protected Response prepareATRowForSave() {
        // Check if transient references are valid and store the corresponding keys in the ATRow:
        Response res = super.prepareATRowForSave();

        return res;
    }

}
