package com.adasoft.gv.phase.product.labelgenerator;

/**
 * This file is generated by the PhaseLibManager
 */
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseDataFilter;

/**
 * Generated class definition
 */
public class MESRtPhaseDataLabelGen0100Filter extends MESGeneratedRtPhaseDataLabelGen0100Filter //nl
        implements IMESRtPhaseDataFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated method definition
     *
     * @param server The Server object
     */
    public MESRtPhaseDataLabelGen0100Filter(Server server) {
        super(server);
    }

    /**
     * Generated method definition
     *
     */
    public MESRtPhaseDataLabelGen0100Filter() {
        super();
    }
}
