package com.adasoft.gv.phase.product.labelgenerator;

/**
 * This file is generated by the PhaseLibManager
 */
import com.datasweep.compatibility.client.ATRow;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseData;

/**
 * Generated class definition
 */
public class MESRtPhaseDataLabelGen0100 extends MESGeneratedRtPhaseDataLabelGen0100 //
                                                  implements IMESRtPhaseData {

    /**
     * Generated method definition
     *
     * @param key The key of the ATRow to load.
     */
    public MESRtPhaseDataLabelGen0100(long key) {
        super(key);
    }

    /**
     * Generated method definition
     *
     * @param source the source to copy.
     */
    public MESRtPhaseDataLabelGen0100(MESRtPhaseDataLabelGen0100 source) {
        super(source);
    }

    /**
     * Generated method definition
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESRtPhaseDataLabelGen0100(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated method definition
     *
     */
    public MESRtPhaseDataLabelGen0100() {
        super();
    }

}
