package com.adasoft.gv.phase.product.labelgenerator;

import com.rockwell.mes.commons.shared.phase.mvc.AbstractPhaseExceptionView0200;

/**
 * TODO: Runtime phase exception view.
 * <p>
 * Skeleton generated by the PhaseLibManager.
 * <p>
 * 
 * TODO: @author UserName, (c) Copyright 2013 Rockwell Automation Technologies, Inc. All Rights Reserved.
 */
public class RtPhaseExceptionViewLabelGen0100 extends AbstractPhaseExceptionView0200<RtPhaseModelLabelGen0100> {

    /** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;

    /**
     * @param theModel the given model
     */
    public RtPhaseExceptionViewLabelGen0100(final RtPhaseModelLabelGen0100 theModel) {
        super(theModel);
    }

    @Override
    protected void createUI() {
    }

}
