package com.adasoft.gv.phase.product.labelgenerator;

import com.rockwell.mes.commons.shared.phase.mvc.AbstractPhaseActionView0200;

/**
 * TODO: Runtime phase action view.
 * <p>
 * Skeleton generated by the PhaseLibManager.
 * <p>
 * 
 * TODO: @author UserName, (c) Copyright 2013 Rockwell Automation Technologies, Inc. All Rights Reserved.
 */
public class RtPhaseActionViewLabelGen0100 extends AbstractPhaseActionView0200<RtPhaseModelLabelGen0100> {

    /** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = 1L;

    /**
     * @param theModel the given model
     */
    public RtPhaseActionViewLabelGen0100(final RtPhaseModelLabelGen0100 theModel) {
        super(theModel);
    }

}
