package com.adasoft.gv.phase.product.labelgenerator;

import com.rockwell.mes.commons.shared.phase.mvc.AbstractPhaseModel0200;

/**
 * TODO: Runtime phase model.
 * <p>
 * Skeleton generated by the PhaseLibManager.
 * <p>
 * 
 * TODO: @author UserName, (c) Copyright 2013 Rockwell Automation Technologies, Inc. All Rights Reserved.
 */
public class RtPhaseModelLabelGen0100 extends AbstractPhaseModel0200 {

    /**
     * @param inPhaseExecutor The phase executor of this model
     */
    protected RtPhaseModelLabelGen0100(final RtPhaseExecutorLabelGen0100 inPhaseExecutor) {
        super(inPhaseExecutor);
    }

    /**
     * @return Returns the executor.
     */
    public RtPhaseExecutorLabelGen0100 getExecutor() {
        return (RtPhaseExecutorLabelGen0100) executor;
    }

    @Override
    public boolean init() {
        // TODO Auto-generated method stub
        return true;
    }
}
