package com.rockwell.mes.myeig.model;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

/**
 * Generated class definition for application table MY_EigPersistentObjects.
 * Application table description: null
 */
public class MESMyEigPersistentObjects extends MESGeneratedMyEigPersistentObjects {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESMyEigPersistentObjects(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESMyEigPersistentObjects(MESMyEigPersistentObjects source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESMyEigPersistentObjects(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESMyEigPersistentObjects() {
        super();
    }

}
