package com.rockwell.mes.myeig.model;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

/**
 * Generated filter class for application table MY_EigPersistentObjects.
 */
public class MESMyEigPersistentObjectsFilter extends MESGeneratedMyEigPersistentObjectsFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESMyEigPersistentObjectsFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESMyEigPersistentObjectsFilter() {
        super();
    }
}
